language: ruby
sudo: false
cache: bundler
bundler_args: '--path vendor/bundle'
gemfile:
  - gemfiles/32.gemfile
  - gemfiles/41.gemfile
  - gemfiles/42.gemfile
rvm:
  - 2.2.4
  - 2.3.0
env:
  - REAL=1
  - TEST=1
script: bundle exec rake spec
